### PR TITLE
Fix DevideByZeroError

### PR DESCRIPTION
**Pull request by joostlek**
This will fix https://github.com/home-assistant/core/issues/97765

### CODE REVIEW

**Review by frenck — APPROVED** [review]

**Comment by joostlek** [comment]
Don't forget to merge it ;)

**Comment by frenck** [comment]
> Don't forget to merge it ;)

CI is failing, not sure on the state of this repo. I don't own Toon anymore. Will check later.

**Comment by tne7laa** [comment]
What is the status? I changed de source code locally now with vi editor myself.

**Comment by joostlek** [comment]
Euh, this repo doesn't have a lot of CI/CD, so the deploy has to go manually. The ball is now at Frenck.

**Pull request merged**
